### ISSUE TITLE
defining namespaced variables of a custom Type in that namespace

### ISSUE THREAD

**Issue by AK1089** [Lightwood13/msc#2]
When creating a new namespace `example` which contains the Type `Class` [with a constructor `Class()` and field `data`], and a namespaced variable `var` of Type `Class`:

1. the Type `Class` is defined.
2. the field `data` is defined within `Class`.
3. the constructor `Class()` is defined.
4. the variable `var` is defined, with value equal to `Class()`.
5. the constructor script for `Class()` is imported.

This is mostly expected behaviour, however there is one issue: the value of `var` has been set to a `null` instance of `Class.` This is because at define-time, the constructor used in the variable's definition (constructor `Class()`) has been _defined_ but not _imported_.

**Note also that a similar problem likely exists with variables which are initialised as the result of a namespaced function.**

This causes a silent fail (there is no error message, and `var` is "successfully" defined as an instance, but the constructor does not function correctly). This can be verified using the `data` field or equivalent: even if `Class()` sets `data`, the field will be blank.

Unfortunately, fixing might be difficult. Variables can depend on constructors being imported (as in the given example), but constructors might equally depend on variables existing with a value, so imports cannot always precede variables. Maintaining a tree of dependencies for each script and variable might be the only complete solution. Alternatively, perhaps import constructors and functions "early" if and only if variables depend on them, though this might still cause edge case* issues.

*Particularly, note that **imports are handled asynchronously**: you have to account for a delay of up to ~1 second in order to _guarantee_ that a constructor has **finished** importing before referencing it.

[Reference 1](https://discord.com/channels/190350281580478466/488226184648458241/960196148407181352) - original namespace file showing issue
[Reference 2](https://discord.com/channels/190350281580478466/488226184648458241/960202810413170799) - script generated by plugin for this namespace file
[Reference 3](https://discord.com/channels/190350281580478466/488226184648458241/960208846234722304) - wild edge case / worst-case scenario

**Comment by Lightwood13** [comment]
Fixed in version 2.1.10

Variable definitions were split into declaration and initialization, and initialization moved to the end of import script.
